### ISSUE TITLE
TypeError (no implicit conversion of Hash into String)

### ISSUE THREAD

**Issue by rg-ac** [vvmruder/redmine_doc_pu#13]
We tried the redmine_doc_pu on the following setup:

Linux Ubuntu 14.04
Redmine version                3.2.8.stable
Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
Rails version                  4.2.7.1

We can create new documents under 'Publish', but when the Build is started, there is an Internal error and the logfile says:

TypeError (no implicit conversion of Hash into String):
  plugins/redmine_doc_pu/lib/textile_doc_latex.rb:207:in `to'
  plugins/redmine_doc_pu/lib/textile_doc_latex.rb:207:in `to_latex'
  plugins/redmine_doc_pu/lib/latex_wiki_page.rb:60:in `to_latex'
  plugins/redmine_doc_pu/app/models/doc_pu_wiki_page.rb:24:in `to_latex'
  plugins/redmine_doc_pu/lib/latex_doc.rb:67:in `block in to_latex'
  plugins/redmine_doc_pu/lib/latex_doc.rb:66:in `to_latex'
  plugins/redmine_doc_pu/lib/latex_doc.rb:120:in `build'
  plugins/redmine_doc_pu/app/models/doc_pu_document.rb:27:in `build'
  plugins/redmine_doc_pu/app/controllers/doc_pu_controller.rb:101:in `build_remote'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by rg-ac** [comment]
We also tried it with ruby 2.1.5 - same problem.

**Comment by vvmruder** [comment]
Sorry, I'am blocked by other projects. But I will try to look at it soon.

**Comment by rg-ac** [comment]
It might sound strange but it is triggered by the content of the wiki page. If I create a new wiki page with just the content "foo" it works as expected. If I edit the wiki page to have "@foo@" as the content I have the problem described above.
